;* Assembly includefile generated by RevUp 1.5 *

VERSION		EQU	4
REVISION	EQU	503
DATE	MACRO
		dc.b	'10.11.98'
	ENDM
VERS	MACRO
		dc.b	'ahi.device 4.503'
	ENDM
VSTRING	MACRO
		dc.b	'ahi.device 4.503 (10.11.98)',13,10,0
	ENDM
VERSTAG	MACRO
		dc.b	0,'$VER: ahi.device 4.503 (10.11.98)',0
	ENDM
